#!usr/bin/env bash  

#Create a VPC
VPC_ID=(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc}]' \
--region us-east-1 \
--query Vpc.VpcId \
--output text)
echo "VPC_ID: $VPC_ID"

#Create an IGW 
IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text)

echo "IGW_ID: $IGW_ID"

#Attach an IGW 
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID
#Create a new subnet 
SUBNET_ID=(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block 172.1.0.0/16 \
--query Subnet.SubnetId \
--output text)

echo "SUBNET_ID $SUBNET_ID"
#Explicitly associate subnet 
RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query "RouteTables[].RouteTableId[]" \
--output text)
echo "RT_ID: $RT_ID"

aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID

#Add a Route to RouteTable to IGW 

aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID

